apiVersion: v1
kind: PersistentVolume
metadata:
  name: lazylibrarian-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.10.10.200
    path: /mnt/ghostdata/ghostsilo/99_System/K8S-Data/media/lazylibrarian
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lazylibrarian-config-pvc
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: lazylibrarian-config-pv
  resources:
    requests:
      storage: 2Gi
