apiVersion: v1
kind: PersistentVolume
metadata:
  name: searxng-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.10.200
    path: /mnt/ghostdata/ghostsilo/99_System/K8S-Data/searxng
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-pvc
  namespace: personal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: searxng-pv
  resources:
    requests:
      storage: 5Gi
